### ISSUE TITLE
I need boilerplate supertokens docs implementation on NEXTJS13 (use app dir)

### ISSUE THREAD

**Issue by syukranDev** [supertokens/supertokens-core#644] opened 2023-04-23 08:15 UTC
## 📚 Documentation

As per issue subject, I tried implemented supertoken implemented in NEXTJS13 using old supertokens nextJS12 but it was unsuccessful attempt.

Anybody have any template in their Git on implementing Supertoken in new NEXTJS13 (the one that use app DIR), please share one. 

Much appreciated <3

**Comment by rishabhpoddar** [comment] 2023-04-23 13:32
Hey @syukranDev - i just tried our nextjs demo app (using next13 with old next12 structure). This does not use the app directory, but it does work.

We will be making changes to support the app directory very soon, but until then, try out of demo app using `npx create-supertokens-app@latest`.

For now, i am closing this issue cause it's a duplicate of https://github.com/supertokens/supertokens-auth-react/issues/669

**Closed by rishabhpoddar** 2023-04-23 13:32 UTC
Labels: documentation

**Comment by syukranDev** [comment] 2023-04-23 13:34
Might as well update your docs to not use in next13 with app dir, its brutally confusing.

**Comment by rishabhpoddar** [comment] 2023-04-24 06:09
> Might as well update your docs to not use in next13 with app dir, its brutally confusing.

Fair enough
