### ISSUE TITLE
unable to build the supertoken projects using ssg methods

### ISSUE THREAD

**Issue by denniarems** [supertokens/supertokens-core#481] opened 2022-07-22 09:27 UTC
## 🐛 Bug Report

using https://github.com/antfu/vitesse template , i got an error while building the project using `pnpm build` comment 
the way i imported 
![image](https://user-images.githubusercontent.com/39432770/180409175-ead9b58a-5674-4f71-9199-27545ac6f0ec.png)

the error i got
![image](https://user-images.githubusercontent.com/39432770/180408199-3ca3d44d-776a-45e5-85fe-4d34ee595dd6.png)

## Useful information
Discord Chat [thread](https://discord.com/channels/603466164219281420/999692170854404207)

**Comment by nkshah2** [comment] 2022-07-22 11:14
@denniarems One of the package loaders in that template seems to be loading external dependencies incorrectly. The import for

```tsx
import ThirdPartyEmailPassword from "supertokens-web-js/recipe/thirdpartyemailpassword";
```

Gets converted to

```tsx
import ThirdPartyEmailPassword from "supertokens-web-js/recipe/thirdpartyemailpassword.js";
```

In production modes, which is invalid because that file does not exist. Since this is not a bug in the SDK, theres no real fix here.

As a workaround you can change your import to be 

```tsx
import ThirdPartyEmailPassword from "supertokens-web-js/recipe/thirdpartyemailpassword/index";
```

Which works for both debug and production builds.

PS: Im closing this issue, feel free to reopen it if you still run into problems issues

**Closed by nkshah2** 2022-07-22 11:14 UTC
Labels: bug
