### ISSUE TITLE
Old tokens still work after refreshing then token

### ISSUE THREAD

**Issue by leoujz** [supertokens/supertokens-core#532] opened 2022-11-17 10:20 UTC
I tested the [with-localstorage example](https://github.com/supertokens/supertokens-auth-react/tree/master/examples/with-localstorage), which uses request header `st-cookie` instead of cookie. 
I tested it with Postman, successfully signup and login, and refresh token. After refresing token, I got new accessToken, new refreshToken, new IdRefreshToken, the old tokens(including accessToken, refreshToken) still work. Is that supposed to be still valid after refreshing tokens?

**Comment by rishabhpoddar** [comment] 2022-11-17 11:05
Yea, they are supposed to work cause:
- access token validation happens in a stateless way -> so when it expires, it will stop working
- the old refresh token will stop working (and trigger a token theft detection error) when either the new access token or the new refresh tokens are used.

Closing this issue, since it's not a bug, but is expected behaviour.

**Comment by leoujz** [comment] 2022-11-17 13:00
- is there a way to invalidate the old accesstoken? 
- after refreshing the token, the old refresh token still works, it does not stop working

**Comment by rishabhpoddar** [comment] 2022-11-17 13:03
- Yes. See this: https://supertokens.com/docs/session/common-customizations/sessions/access-token-blacklisting
- The old refresh token will stop working when the new refresh token is used, or when the new access token is used.

**Comment by leoujz** [comment] 2022-11-17 13:26
Thanks very much

**Comment by rishabhpoddar** [comment] 2022-11-17 14:28
not really. If you invalidate the old one, and if that doesn't reach the frontend (cause of some network issue), then the user will be logged out. Instead, we invalidate the old one only when the new access token or the new refresh token is used. In this case, we also invalidate the other "sibling" refresh token that was generated

**Comment by leoujz** [comment] 2022-11-18 02:03
agree, it works, thanks very much. After using new tokens to get sessioninfo, I use old tokens to refresh the token and get empty tokens back, then all tokens are invalidated, that's really great.

**Closed** 2022-11-18 02:03 UTC
Labels: bug
