### ISSUE TITLE
Implementing Supertokens with NextJS 13 App Router

### ISSUE THREAD

**Issue by ashwanip** [supertokens/supertokens-core#684] opened 2023-05-18 14:18 UTC
## 🚀 Feature

Implementing Supertokens with NextJS 13 App Router

## Implementation details

Current implementation guide for integrating Supertokens with NextJS uses NextJS Page Router. Please provide guide to integrate Supertokens with NextJS 13 App Router.

**Comment by rishabhpoddar** [comment] 2023-05-19 05:07
This issue is a duplicate of this: https://github.com/supertokens/supertokens-auth-react/issues/669

**Closed by rishabhpoddar** 2023-05-19 05:08 UTC
Labels: enhancement
