### ISSUE TITLE
context.redirectToPath is undefined after log in

### ISSUE THREAD

**Issue by idanhaviv** [supertokens/supertokens-core#502] opened 2022-09-05 11:51 UTC
## 🐛 Bug Report

I'm trying to redirect the user to the previous location after logging in, following this guide: https://supertokens.com/docs/thirdpartyemailpassword/common-customizations/redirecting-post-login
but after the user completes log in (with Google) the context.redirectToPath is undefined and so this flow doesn't work
i'm using react-router-dom and in case a session doesn't exist I use your api ( redirectToAuth ) to redirect the user to auth screen

## Useful informations

react-router-dom 6.3.0
react 18.2.0

i'm calling getSuperTokensRoutesForReactRouterDom under Routes (as suggested on React guide)
and if a session doesn't exist for an authenticated route i call redirectToAuth() to reroute the user to auth screen

I also can't see any route saved to local storage

**Comment by porcellus** [comment] 2022-09-07 11:30
This seems to be working for me as expected, but maybe I'm missing something from your setup:
- Are you passing `redirectBack` as true to `redirectToAuth`? In case you don't, this is the expected behavior.
- Are you using a custom sign-in/up page?
- What kind of customizations have you added?

**Comment by ironman19933** [comment] 2022-09-07 15:10
porcellus, i am also facing the exact same issue mentioned in the ticket. 
can you please share the sample code which you have written to test this.

**Comment by porcellus** [comment] 2022-09-07 18:26
I've modified our [thirdpartyemailpassword example](https://github.com/supertokens/supertokens-auth-react/tree/master/examples/with-thirdpartyemailpassword):
- added a button that calls `redirectToAuth({redirectBack: true})` on a new route ("/asdf")
- added a `getRedirectionURL` that logs the context to console

**Comment by rishabhpoddar** [comment] 2022-09-08 05:36
@porcellus i don't see any modification to the example app - am I missing something?

**Comment by porcellus** [comment] 2022-09-08 14:45
That's how I tested it locally - not committed to the repo.

**Comment by rishabhpoddar** [comment] 2022-09-11 10:00
Ah i see. So using `redirectToAuth({redirectBack: true})` solves this issue. Since this is not a bug, I am closing this issue. But feel free to reopen if I misunderstood.

**Closed by rishabhpoddar** 2022-09-11 10:00 UTC
Labels: bug

**Comment by idanhaviv** [comment] 2022-09-14 18:38
@porcellus it works! thank you!
