### ISSUE TITLE
Supertokens not working with node version 18.12.1

### ISSUE THREAD

**Issue by ishanjain1502** [supertokens/supertokens-core#852] opened 2023-10-18 06:48 UTC
## 🐛 Bug Report

Supertokens web sdk version 0.8.0 is failing to run on node version 18.12.1 nextjs version 13.5.5, with a typeError

## Useful informations

output on terminal
![image](https://github.com/supertokens/supertokens-core/assets/56102033/bccad9a6-589d-4ad7-aee3-01f2914e24c1)

**Comment by nkshah2** [comment] 2023-10-18 10:57
Hi @ishanjain1502 

Looks like the issue occurs on that version of node but does not occur on later versions of Node 18. Can you try upgrading to the latest version of node 18 (18.18.2) and seeing if the issue still occurs for you? Note you will have to delete the `.next` directory after upgrading your node version

**Comment by ishanjain1502** [comment] 2023-10-18 11:02
Hi @nkshah2 
thanks for such quick response.

yeah i also found that its particularly breaking on node version 18.12.1 and working perfect on node > 18.17.x
but the thing is i am using aws elastic beanstalk for deployment, and its lts with amazon linux only supports node 18.12.1, that's why cant change my node version, as the one which supports higher versions is already undergoing migrations

is there any other way to make it work

**Comment by nkshah2** [comment] 2023-10-18 11:04
The issue is being thrown from the NextJS bundle and not from the SuperTokens SDK so there isnt much we can do here. You could try changing the version of next you are using to see if that resolves it (not sure if it will but just throwing out ideas). 

Since this is not something we can solve from our end, I will close this issue.

**Closed by nkshah2** 2023-10-18 11:04 UTC
Labels: bug

**Comment by ishanjain1502** [comment] 2023-10-18 11:35
Thanks for the update @nkshah2

**Comment by ishanjain1502** [comment] 2023-10-18 12:03
> The issue is being thrown from the NextJS bundle and not from the SuperTokens SDK so there isnt much we can do here. You could try changing the version of next you are using to see if that resolves it (not sure if it will but just throwing out ideas). 
> 
> Since this is not something we can solve from our end, I will close this issue.

Do you have any idea regarding which next version we could use for it 👀

**Comment by rishabhpoddar** [comment] 2023-10-19 05:37
The issue is more related to the node version, or then post on the nextjs community.
