### ISSUE TITLE
Add Svelte UI for Supertokens

### ISSUE THREAD

**Issue by Coinhexa** [supertokens/supertokens-core#634] opened 2023-04-07 15:14 UTC
## 🚀 Feature

Quick look at your documentation indicates you have direct support for React, Angular and Vue. Kindly consider adding one for Svelte which is an absolute banger of a frontend framework that doesnt use virtual DOMs.

**Comment by rishabhpoddar** [comment] 2023-04-10 14:28
Duplicate of https://github.com/supertokens/supertokens-core/issues/584

**Closed by rishabhpoddar** 2023-04-10 14:28 UTC
Labels: enhancement
